name: gcloud-function-deployment
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  job_id:
    steps:
      - uses: 'actions/checkout@v3'
        -
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'test-function'
          runtime: 'nodejs16'
