name: gcloud-function-deployment
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: Setup GCP Service Account
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: deploy cloud function
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'testCloudFunction'
          entry_point: 'testCloudFunction'
          runtime: 'nodejs16'
